### PR TITLE
Improve fulcro configuration

### PR DESCRIPTION
**Pull request by cjsauer**
Fulcro comes with a lot of custom macros, and makes heavy use of `.cljc` reader conditionals, which makes configuring `clj-kondo` for a project an act of trial and error. This is the humble beginnings of a Fulcro configuration that seems to be working well for me so far. Hopefully others can build on it further.

I'll continue to update this as I progress in this project if that is desirable.

### CODE REVIEW

**Comment by borkdude** [comment]
@cjsauer Thanks! Can you also add some "tests" like for the other libs? Just code that, while opening in your editor, shows that the config is working like expected.

**Comment by cjsauer** [comment]
I’m still working out the “expected” part of this config. 

Fulcro has a ton of macros and reader conditionals (cljc), and so I’m finding that the right config is a delicate balance...as an example, I ended up disabling the “unused namespace” linter, because it’s very noisy in cljc files (at no fault of kondo’s). But that is a pretty heavy change, and perhaps not one that should be in a blessed Fulcro config. 

I’d like to see what other Fulcro users think/do.

**Comment by borkdude** [comment]
@cjsauer Let's not confuse 2 things here: the config that should go into library is for fulcro users, not for linting the fulcro library itself. As such, it should not include config for taoensso.timbre, etc.

**Comment by cjsauer** [comment]
There are certain libraries that are implied by Fulcro (and in some cases central to it, eg pathom), so my thinking was that 95% of users are going to be adding timbre to their config anyway if they’re starting a new Fulcro project.

**Comment by borkdude** [comment]
@cjsauer I understand, but this should be configured separately so it can be tweaked independently.

**Comment by cjsauer** [comment]
That makes perfect sense. I had glossed over how this project was structured. Each library has its own independent configuration. I stripped out non-fulcro configuration.

I have a semi-working `defmutation` hook in the latest commit, but I'm getting a slightly unexpected lint warning. My strategy is to convert this form:

```Clojure
(defmutation mutation-example1
  "Here is a doc string"
  [params]
  (action [] params)
  (remote [env] true))
```

into this one:

```clojure
(defn mutation-example1
  "Here is a doc string"
  [params]
  (letfn [(action [] params)
          (remote [env] true)]
    [action remote]))
```

Which is working quite well at capturing the intent of `defmutation`. However I'm seeing "unused binding action" and "unused binding remote" in the linter warnings...I'm not sure why that's happening as I'm clearly returning a vector of `[action remote]` functions. If I paste that `letfn` expansion into a file verbatim I don't see those warnings.

**Comment by cjsauer** [comment]
Ah figured it out. The symbols inside of `[action remote]` we're not wrapped in `api/token-node`!

**Comment by borkdude** [comment]
I forgot about this PR, I'm terribly sorry. I'll add it to my TODO list and take a look soon.

**Comment by borkdude** [comment]
Decided to just go ahead and merge, we can make improvements as needed from here. Thanks a lot @cjsauer !

**Comment by cjsauer** [comment]
Awesome, thank you!

**Pull request merged**
